// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registra un nuevo miembro del staff administrativo verificando la jerarquía de permisos.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administración - Gestión"
                ],
                "summary": "Crear un nuevo administrador",
                "parameters": [
                    {
                        "description": "Datos del nuevo administrador y permisos",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.CreateAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "message: creado correctamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "error: datos inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "error: violación de jerarquía",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Realiza un borrado lógico del administrador. No permite auto-eliminación ni borrar SUDO.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administración - Gestión"
                ],
                "summary": "Eliminar administrador (Soft-delete)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID del administrador",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: eliminado correctamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "error: ID inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "error: permisos insuficientes",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna una lista paginada de administradores con soporte para búsqueda y caché.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administración - Gestión"
                ],
                "summary": "Listar administradores",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Número de página (def: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Registros por página (def: 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Búsqueda por username o email",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filtrar por estado activo (true/false)",
                        "name": "active",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data, total, page, limit",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "error: fallo interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/posts": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crea un post con contenido HTML y opcionalmente una imagen.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administración - Publicaciones"
                ],
                "summary": "Publicar nueva noticia",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Título del post",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resumen para el feed",
                        "name": "short_description",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Contenido HTML/Texto",
                        "name": "content",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tipo: public, psi",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Visible inmediatamente",
                        "name": "is_active",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Imagen de portada",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/posts/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Actualiza metadatos e imagen. El ID se obtiene de la URL. Los campos son opcionales (PATCH).",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administración - Publicaciones"
                ],
                "summary": "Actualizar publicación",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de la publicación",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nuevo título",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Descripción corta",
                        "name": "short_description",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Contenido detallado",
                        "name": "content",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Tipo de post",
                        "name": "type",
                        "in": "formData"
                    },
                    {
                        "type": "boolean",
                        "description": "Estado de activación",
                        "name": "is_active",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Nueva imagen de portada",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"message\": \"Publicación actualizada\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "{\"error\": \"Datos inválidos\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/psi/social/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Puede ser usado por el psicólogo dueño o por un Administrador.",
                "tags": [
                    "Psicólogos - Perfil"
                ],
                "summary": "Borrar red social (Soft Delete)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de la red",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/psi/upload-csv": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Procesa un archivo CSV y crea registros. Solo accesible para administradores autorizados.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administración - Psicólogos  \u003c-- Tag corregido para agruparlo bien"
                ],
                "summary": "Importar psicólogos masivamente",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Archivo CSV a procesar",
                        "name": "csv",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Retornado si el usuario no tiene permisos (Security by Obscurity)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/specialties": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registra una especialidad. Solo accesible para administradores autorizados.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administración - Especialidades"
                ],
                "summary": "Crear nueva especialidad",
                "parameters": [
                    {
                        "description": "Datos de la nueva especialidad",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.CreateSpecialtyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "message: Especialidad creada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "error: permiso denegado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/specialties/all": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna todas las especialidades sin filtros de estado. Uso para paneles de gestión.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administración - Especialidades"
                ],
                "summary": "Listado administrativo total",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_domain.PsiSpecialtyModel"
                            }
                        }
                    },
                    "403": {
                        "description": "error: permisos insuficientes",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/specialties/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Marca una especialidad como inactiva. Solo Admin.",
                "tags": [
                    "Administración - Especialidades"
                ],
                "summary": "Eliminar especialidad (Soft-delete)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la especialidad",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: Especialidad desactivada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Modifica campos de una especialidad. Actualiza automáticamente la auditoría (UpdateBy).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administración - Especialidades"
                ],
                "summary": "Actualizar especialidad",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la especialidad",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Campos parciales a modificar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.UpdateSpecialtyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: Especialidad actualizada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "error: permiso denegado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/update": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Modifica los datos y permisos de un administrador. Actualiza automáticamente la auditoría.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administración - Gestión"
                ],
                "summary": "Actualizar administrador",
                "parameters": [
                    {
                        "description": "Campos parciales a actualizar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.UpdateAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: actualizado correctamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "error: permiso denegado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Valida las credenciales del administrador (email o username) y retorna un JWT dinámico.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administración - Auth"
                ],
                "summary": "Iniciar sesión administrativo",
                "parameters": [
                    {
                        "description": "Credenciales de acceso",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message, token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "error: formato inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "error: credenciales inválidas",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/posts": {
            "get": {
                "description": "Obtiene noticias. El contenido varía según el usuario: Público (solo noticias generales), Psicólogo (generales + gremiales), Admin (todo).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Publicaciones"
                ],
                "summary": "Listar noticias y publicaciones",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Número de página (Default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items por página (Default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data, total, page",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/posts/{id}": {
            "get": {
                "description": "Devuelve el detalle de la noticia incluyendo el contenido HTML. Valida permisos de visibilidad.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Publicaciones"
                ],
                "summary": "Obtener noticia por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID del Post",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_domain.Post"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/psi/directory": {
            "get": {
                "description": "Busca psicólogos. Si se usa 'q' (Nombre/CI/FPV), ignora solvencia. Si no, solo muestra solventes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Psicólogos - Público"
                ],
                "summary": "Directorio Público (Mini Perfiles)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Búsqueda por Identidad",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtro especialidad (Solo en navegación)",
                        "name": "specialty",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Límite",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/psi/login": {
            "post": {
                "description": "Autentica a un agremiado y retorna un token de sesión.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Psicólogos - Auth"
                ],
                "summary": "Login de Psicólogo",
                "parameters": [
                    {
                        "description": "Credenciales",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.PsiLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/psi/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna toda la información del psicólogo autenticado (sin aplicar filtros de privacidad o solvencia). Ideal para el Dashboard del usuario.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Psicólogos - Perfil"
                ],
                "summary": "Obtener mi propio perfil (Autogestión)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_domain.PsiUserModel"
                        }
                    },
                    "401": {
                        "description": "No autorizado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permite al psicólogo actualizar su información de contacto y visibilidad.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Psicólogos - Perfil"
                ],
                "summary": "Actualizar mi perfil",
                "parameters": [
                    {
                        "description": "Datos editables",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.PsiUserUpdateRequestSelf"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/psi/me/postgrades": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registra un título académico y permite subir hasta 3 imágenes (título, notas, etc).",
                "consumes": [
                    "multipart/form-data   \u003c-- CAMBIO IMPORTANTE"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Psicólogos - Académico"
                ],
                "summary": "Agregar postgrado con soportes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Título obtenido",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Universidad",
                        "name": "university",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Año de graduación",
                        "name": "graduation_year",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Descripción opcional",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Imagen del Título",
                        "name": "pic_one",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Imagen de Notas",
                        "name": "pic_two",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Imagen Extra",
                        "name": "pic_three",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/psi/me/postgrades/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Edita un título. Permite reemplazar imágenes específicas enviando 'pic_one', 'pic_two' o 'pic_three'.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Psicólogos - Académico"
                ],
                "summary": "Actualizar postgrado",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del Postgrado",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Título obtenido",
                        "name": "title",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Universidad",
                        "name": "university",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Año",
                        "name": "graduation_year",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Descripción",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Reemplazar Imagen 1",
                        "name": "pic_one",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Reemplazar Imagen 2",
                        "name": "pic_two",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Reemplazar Imagen 3",
                        "name": "pic_three",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "No es tu registro",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/psi/me/social": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Psicólogos - Perfil"
                ],
                "summary": "Agregar red social",
                "parameters": [
                    {
                        "description": "Datos de la red",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.CreateSocialNetworkRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/psi/me/social/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Puede ser usado por el psicólogo dueño o por un Administrador.",
                "tags": [
                    "Psicólogos - Perfil"
                ],
                "summary": "Borrar red social (Soft Delete)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de la red",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Psicólogos - Perfil"
                ],
                "summary": "Actualizar red social",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de la red",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Campos parciales",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.UpdateSocialNetworkRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/psi/{id}": {
            "get": {
                "description": "Retorna la ficha técnica. Oculta datos privados (teléfono, email) según configuración del usuario.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Psicólogos - Público"
                ],
                "summary": "Ver perfil público de psicólogo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID del Psicólogo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.PsiFullProfileDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/specialties": {
            "get": {
                "description": "Retorna el catálogo. Los usuarios ven solo las activas. Admins con permiso pueden filtrar por ?status=active|inactive|all.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catálogos - Especialidades"
                ],
                "summary": "Listar especialidades (Público/Admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filtro administrativo: active, inactive, all (Default: active)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_domain.PsiSpecialtyModel"
                            }
                        }
                    },
                    "500": {
                        "description": "error al recuperar especialidades",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/specialties/count": {
            "get": {
                "description": "Obtiene el número total. Público: solo activas. Admin: permite filtrar por ?active=true|false.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catálogos - Especialidades"
                ],
                "summary": "Contar total de especialidades",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Filtrar por estado (Solo Admins)",
                        "name": "active",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "count",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                            }
                        }
                    }
                }
            }
        },
        "/specialties/{id}": {
            "get": {
                "description": "Retorna el detalle completo de una especialidad específica mediante su ID numérico.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catálogos - Especialidades"
                ],
                "summary": "Obtener especialidad por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID único de la especialidad (uint32)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_domain.PsiSpecialtyModel"
                        }
                    },
                    "400": {
                        "description": "ID inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "especialidad no encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_veniversvm_ColPsiCarabobo_api_internal_domain.Post": {
            "type": "object",
            "properties": {
                "create_by": {
                    "description": "CreateBy almacena el nombre o identificador textual del creador.",
                    "type": "string"
                },
                "create_by_id": {
                    "description": "CreateById es el UUID del usuario/administrador que creó el registro.\nEs un puntero para permitir valores nulos si la creación es automática por el sistema.",
                    "type": "string"
                },
                "created_at": {
                    "description": "CreatedAt registra la fecha y hora exacta en que se creó el registro.\nGORM gestiona este campo automáticamente durante la inserción.",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "description": "ImageS3Key almacena la ruta (Key) del archivo de imagen en el bucket de AWS S3/MinIO.\nNo guardamos la URL completa para mantener flexibilidad si cambia el dominio del bucket.",
                    "type": "string"
                },
                "is_active": {
                    "description": "IsActive permite el control de visibilidad (Borrador/Publicado).",
                    "type": "boolean"
                },
                "short_description": {
                    "description": "ShortDescription actúa como un 'snippet' o resumen para las vistas de lista.\nAyuda al SEO y a la experiencia de usuario antes de entrar al detalle.",
                    "type": "string"
                },
                "text": {
                    "description": "Text es la instancia cargada del contenido.\nGORM permite cargar este campo mediante 'Preload' cuando se requiere el detalle completo.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_domain.TextModel"
                        }
                    ]
                },
                "text_id": {
                    "description": "Relación con el texto largo.\nTextID es la clave foránea que apunta al contenido extenso en TextModel.",
                    "type": "string"
                },
                "title": {
                    "description": "Title es el encabezado de la publicación.\nLimitado a 100 caracteres para optimizar la visualización en el frontend.",
                    "type": "string"
                },
                "type": {
                    "description": "Type define el alcance de la publicación.\nValores comunes: \"public\" (abierto a todos), \"psi\" (solo psicólogos logueados).",
                    "type": "string"
                },
                "update_by": {
                    "description": "UpdateBy almacena el nombre o identificador textual de la última persona en modificarlo.",
                    "type": "string"
                },
                "update_by_id": {
                    "description": "UpdateById es el UUID del usuario/administrador que realizó la última actualización.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt registra la última fecha y hora en que se modificó el registro.\nGORM actualiza este valor automáticamente en cada operación de guardado.",
                    "type": "string"
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_domain.PsiSpecialtyModel": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "create_by": {
                    "description": "CreateBy almacena el nombre o identificador textual del creador.",
                    "type": "string"
                },
                "create_by_id": {
                    "description": "CreateById es el UUID del usuario/administrador que creó el registro.\nEs un puntero para permitir valores nulos si la creación es automática por el sistema.",
                    "type": "string"
                },
                "created_at": {
                    "description": "CreatedAt registra la fecha y hora exacta en que se creó el registro.\nGORM gestiona este campo automáticamente durante la inserción.",
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "update_by": {
                    "description": "UpdateBy almacena el nombre o identificador textual de la última persona en modificarlo.",
                    "type": "string"
                },
                "update_by_id": {
                    "description": "UpdateById es el UUID del usuario/administrador que realizó la última actualización.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt registra la última fecha y hora en que se modificó el registro.\nGORM actualiza este valor automáticamente en cada operación de guardado.",
                    "type": "string"
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_domain.PsiUserColData": {
            "type": "object",
            "properties": {
                "cpsm": {
                    "type": "boolean"
                },
                "create_by": {
                    "description": "CreateBy almacena el nombre o identificador textual del creador.",
                    "type": "string"
                },
                "create_by_id": {
                    "description": "CreateById es el UUID del usuario/administrador que creó el registro.\nEs un puntero para permitir valores nulos si la creación es automática por el sistema.",
                    "type": "string"
                },
                "created_at": {
                    "description": "CreatedAt registra la fecha y hora exacta en que se creó el registro.\nGORM gestiona este campo automáticamente durante la inserción.",
                    "type": "string"
                },
                "date_of_last_solvency": {
                    "description": "Histórico de solvencia y membresías dobles.",
                    "type": "string"
                },
                "double_guild": {
                    "type": "boolean"
                },
                "graduate_date": {
                    "type": "string"
                },
                "guild_collaborator": {
                    "type": "boolean"
                },
                "guild_director": {
                    "description": "Professional Flags: Roles y estatus especiales dentro del gremio.",
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "mention_undergraduate": {
                    "type": "string"
                },
                "psi_user_model_id": {
                    "type": "string"
                },
                "public_employee": {
                    "type": "boolean"
                },
                "register_folio": {
                    "type": "string"
                },
                "register_number": {
                    "type": "integer"
                },
                "register_title_date": {
                    "type": "string"
                },
                "register_title_state": {
                    "description": "Register Title: Datos de registro legal del título en el estado.",
                    "type": "string"
                },
                "register_tome": {
                    "type": "string"
                },
                "show_graduate_date": {
                    "type": "boolean"
                },
                "show_mention_undergraduate": {
                    "type": "boolean"
                },
                "show_university_undergraduate": {
                    "type": "boolean"
                },
                "sixty_five_or_plus": {
                    "type": "boolean"
                },
                "university_professor": {
                    "type": "boolean"
                },
                "university_undergraduate": {
                    "description": "Undergraduate Data: Información sobre el título de pregrado.",
                    "type": "string"
                },
                "update_by": {
                    "description": "UpdateBy almacena el nombre o identificador textual de la última persona en modificarlo.",
                    "type": "string"
                },
                "update_by_id": {
                    "description": "UpdateById es el UUID del usuario/administrador que realizó la última actualización.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt registra la última fecha y hora en que se modificó el registro.\nGORM actualiza este valor automáticamente en cada operación de guardado.",
                    "type": "string"
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_domain.PsiUserModel": {
            "type": "object",
            "properties": {
                "bio_text_id": {
                    "type": "string"
                },
                "born_date": {
                    "type": "string"
                },
                "cel_phone_carabobo": {
                    "type": "string"
                },
                "cel_phone_outside_carabobo": {
                    "type": "string"
                },
                "ci": {
                    "description": "CI es la Cédula de Identidad del profesional.",
                    "type": "integer"
                },
                "col_data": {
                    "description": "Relaciones: Conexión con datos académicos y gremiales.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_domain.PsiUserColData"
                        }
                    ]
                },
                "contact_email": {
                    "description": "Contact \u0026 Privacy: Control de visibilidad para el directorio público.",
                    "type": "string"
                },
                "create_by": {
                    "description": "CreateBy almacena el nombre o identificador textual del creador.",
                    "type": "string"
                },
                "create_by_id": {
                    "description": "CreateById es el UUID del usuario/administrador que creó el registro.\nEs un puntero para permitir valores nulos si la creación es automática por el sistema.",
                    "type": "string"
                },
                "created_at": {
                    "description": "CreatedAt registra la fecha y hora exacta en que se creó el registro.\nGORM gestiona este campo automáticamente durante la inserción.",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "description": "Identity: Datos básicos de identificación legal.",
                    "type": "string"
                },
                "fpv": {
                    "description": "FPV es el Número de Federación de Psicólogos de Venezuela.",
                    "type": "integer"
                },
                "genre": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "last_name": {
                    "type": "string"
                },
                "mini_bio": {
                    "description": "Bio: Información profesional resumida y detallada.",
                    "type": "string"
                },
                "municipality_carabobo": {
                    "description": "Location Carabobo: Ubicación dentro de la jurisdicción principal.",
                    "type": "string"
                },
                "municipality_outside_carabobo": {
                    "type": "string"
                },
                "nationality": {
                    "type": "string"
                },
                "phone_carabobo": {
                    "type": "string"
                },
                "phone_outside_carabobo": {
                    "type": "string"
                },
                "post_grades": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_domain.PsiUserPostGrade"
                    }
                },
                "primary_specialty": {
                    "description": "Especialidades: Categorización profesional.",
                    "type": "string"
                },
                "profile_picture_url": {
                    "type": "string"
                },
                "proof_of_life": {
                    "type": "boolean"
                },
                "public_phone": {
                    "type": "string"
                },
                "second_last_name": {
                    "type": "string"
                },
                "second_name": {
                    "type": "string"
                },
                "secondary_specialty": {
                    "type": "string"
                },
                "service_address": {
                    "type": "string"
                },
                "show_contact_email": {
                    "type": "boolean"
                },
                "show_public_phone": {
                    "type": "boolean"
                },
                "show_public_service_address": {
                    "type": "boolean"
                },
                "social_networks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_domain.PsiUserSocialNetwork"
                    }
                },
                "solvent": {
                    "description": "Status \u0026 Files: Estado de solvencia y archivos multimedia.",
                    "type": "boolean"
                },
                "state_outside": {
                    "description": "Location Outside: Ubicación para miembros en el exterior o fuera de Carabobo.",
                    "type": "string"
                },
                "update_by": {
                    "description": "UpdateBy almacena el nombre o identificador textual de la última persona en modificarlo.",
                    "type": "string"
                },
                "update_by_id": {
                    "description": "UpdateById es el UUID del usuario/administrador que realizó la última actualización.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt registra la última fecha y hora en que se modificó el registro.\nGORM actualiza este valor automáticamente en cada operación de guardado.",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_domain.PsiUserPostGrade": {
            "type": "object",
            "properties": {
                "create_by": {
                    "description": "CreateBy almacena el nombre o identificador textual del creador.",
                    "type": "string"
                },
                "create_by_id": {
                    "description": "CreateById es el UUID del usuario/administrador que creó el registro.\nEs un puntero para permitir valores nulos si la creación es automática por el sistema.",
                    "type": "string"
                },
                "created_at": {
                    "description": "CreatedAt registra la fecha y hora exacta en que se creó el registro.\nGORM gestiona este campo automáticamente durante la inserción.",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "pic_one_url": {
                    "description": "S3 Keys para certificados: Almacenan los comprobantes académicos en S3.",
                    "type": "string"
                },
                "pic_three_url": {
                    "type": "string"
                },
                "pic_two_url": {
                    "type": "string"
                },
                "post_grade_description": {
                    "type": "string"
                },
                "post_grade_graduation_year": {
                    "type": "string"
                },
                "post_grade_title": {
                    "type": "string"
                },
                "post_grade_university": {
                    "type": "string"
                },
                "psi_user_id": {
                    "type": "string"
                },
                "update_by": {
                    "description": "UpdateBy almacena el nombre o identificador textual de la última persona en modificarlo.",
                    "type": "string"
                },
                "update_by_id": {
                    "description": "UpdateById es el UUID del usuario/administrador que realizó la última actualización.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt registra la última fecha y hora en que se modificó el registro.\nGORM actualiza este valor automáticamente en cada operación de guardado.",
                    "type": "string"
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_domain.PsiUserSocialNetwork": {
            "type": "object",
            "properties": {
                "create_by": {
                    "description": "CreateBy almacena el nombre o identificador textual del creador.",
                    "type": "string"
                },
                "create_by_id": {
                    "description": "CreateById es el UUID del usuario/administrador que creó el registro.\nEs un puntero para permitir valores nulos si la creación es automática por el sistema.",
                    "type": "string"
                },
                "created_at": {
                    "description": "CreatedAt registra la fecha y hora exacta en que se creó el registro.\nGORM gestiona este campo automáticamente durante la inserción.",
                    "type": "string"
                },
                "is_active": {
                    "description": "IsActive permite al usuario ocultar una red sin borrarla físicamente",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name identifica la plataforma (ej: \"Instagram\", \"LinkedIn\", \"Web Personal\")",
                    "type": "string"
                },
                "psi_user_id": {
                    "type": "string"
                },
                "update_by": {
                    "description": "UpdateBy almacena el nombre o identificador textual de la última persona en modificarlo.",
                    "type": "string"
                },
                "update_by_id": {
                    "description": "UpdateById es el UUID del usuario/administrador que realizó la última actualización.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt registra la última fecha y hora en que se modificó el registro.\nGORM actualiza este valor automáticamente en cada operación de guardado.",
                    "type": "string"
                },
                "url": {
                    "description": "URL es el enlace directo al perfil o página",
                    "type": "string"
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_domain.TextModel": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Content almacena el texto enriquecido o extenso.\nSe define como tipo 'text' en Postgres para permitir longitud ilimitada.",
                    "type": "string"
                },
                "create_by": {
                    "description": "CreateBy almacena el nombre o identificador textual del creador.",
                    "type": "string"
                },
                "create_by_id": {
                    "description": "CreateById es el UUID del usuario/administrador que creó el registro.\nEs un puntero para permitir valores nulos si la creación es automática por el sistema.",
                    "type": "string"
                },
                "created_at": {
                    "description": "CreatedAt registra la fecha y hora exacta en que se creó el registro.\nGORM gestiona este campo automáticamente durante la inserción.",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "update_by": {
                    "description": "UpdateBy almacena el nombre o identificador textual de la última persona en modificarlo.",
                    "type": "string"
                },
                "update_by_id": {
                    "description": "UpdateById es el UUID del usuario/administrador que realizó la última actualización.",
                    "type": "string"
                },
                "updated_at": {
                    "description": "UpdatedAt registra la última fecha y hora en que se modificó el registro.\nGORM actualiza este valor automáticamente en cada operación de guardado.",
                    "type": "string"
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.AdminPermissionsDTO": {
            "type": "object",
            "properties": {
                "can_create_admin": {
                    "type": "boolean"
                },
                "can_create_psi": {
                    "type": "boolean"
                },
                "can_create_tags": {
                    "type": "boolean"
                },
                "can_delete_admin": {
                    "type": "boolean"
                },
                "can_delete_psi": {
                    "type": "boolean"
                },
                "can_delete_publish": {
                    "type": "boolean"
                },
                "can_delete_tags": {
                    "type": "boolean"
                },
                "can_edit_tags": {
                    "type": "boolean"
                },
                "can_manage_notifications": {
                    "type": "boolean"
                },
                "can_publish": {
                    "type": "boolean"
                },
                "can_read_notifications": {
                    "type": "boolean"
                },
                "can_send_notifications": {
                    "type": "boolean"
                },
                "can_update_admin": {
                    "type": "boolean"
                },
                "can_update_psi": {
                    "type": "boolean"
                },
                "can_update_publish": {
                    "type": "boolean"
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.CreateAdminRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "permissions": {
                    "description": "Permisos que se le quieren asignar",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.AdminPermissionsDTO"
                        }
                    ]
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.CreateSocialNetworkRequest": {
            "type": "object",
            "required": [
                "name",
                "url"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "ig"
                },
                "url": {
                    "type": "string",
                    "example": "https://instagram.com/psicologo"
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.CreateSpecialtyRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Especialidad enfocada en..."
                },
                "name": {
                    "type": "string",
                    "example": "Psicología Clínica"
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.PostGradeDTO": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                },
                "university": {
                    "type": "string"
                },
                "year": {
                    "type": "string"
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.PsiFullProfileDTO": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "email": {
                    "description": "Contacto (Condicional)",
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "fpv": {
                    "type": "integer"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "description": "Identidad Pública",
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "location": {
                    "description": "Ubicación",
                    "type": "object",
                    "properties": {
                        "full_address": {
                            "type": "string"
                        },
                        "municipality": {
                            "type": "string"
                        },
                        "state": {
                            "type": "string"
                        }
                    }
                },
                "mini_bio": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "post_grades": {
                    "description": "Postgrados (Siempre visibles si existen)",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.PostGradeDTO"
                    }
                },
                "profile_picture": {
                    "type": "string"
                },
                "social_networks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.SocialNetworkDTO"
                    }
                },
                "solvent": {
                    "type": "boolean"
                },
                "specialties": {
                    "description": "Profesional y Académico",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "undergraduate": {
                    "description": "Datos Universitarios (Condicional)",
                    "type": "object",
                    "properties": {
                        "date": {
                            "type": "string"
                        },
                        "mention": {
                            "type": "string"
                        },
                        "university": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.PsiLoginRequest": {
            "type": "object",
            "required": [
                "identifier",
                "password"
            ],
            "properties": {
                "identifier": {
                    "type": "string",
                    "example": "psicologo@email.com"
                },
                "password": {
                    "type": "string",
                    "example": "12345678"
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.PsiUserUpdateRequestSelf": {
            "type": "object",
            "properties": {
                "cel_phone_carabobo": {
                    "type": "string"
                },
                "cel_phone_outside_carabobo": {
                    "type": "string"
                },
                "contact_email": {
                    "description": "Datos de Contacto y Privacidad (Permitido)",
                    "type": "string"
                },
                "mini_bio": {
                    "description": "Biografía (Permitido)",
                    "type": "string"
                },
                "municipality_carabobo": {
                    "description": "Ubicación (Permitido)",
                    "type": "string"
                },
                "municipality_outside_carabobo": {
                    "type": "string"
                },
                "phone_carabobo": {
                    "type": "string"
                },
                "phone_outside_carabobo": {
                    "type": "string"
                },
                "primary_specialty": {
                    "description": "Especialidades (Permitido, si no está en la tabla de catálogo)",
                    "type": "string"
                },
                "public_phone": {
                    "type": "string"
                },
                "secondary_specialty": {
                    "type": "string"
                },
                "service_address": {
                    "type": "string"
                },
                "show_contact_email": {
                    "type": "boolean"
                },
                "show_graduate_date": {
                    "type": "boolean"
                },
                "show_mention_undergraduate": {
                    "type": "boolean"
                },
                "show_public_phone": {
                    "type": "boolean"
                },
                "show_public_service_address": {
                    "type": "boolean"
                },
                "show_university_undergraduate": {
                    "description": "Campos de ColData",
                    "type": "boolean"
                },
                "state_outside": {
                    "type": "string"
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.SocialNetworkDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.UpdateAdminRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "permissions": {
                    "description": "Permisos",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.AdminPermissionsDTO"
                        }
                    ]
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.UpdateSocialNetworkRequest": {
            "type": "object",
            "properties": {
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "example": "Instagram"
                },
                "url": {
                    "type": "string",
                    "example": "https://instagram.com/nuevo_perfil"
                }
            }
        },
        "github_com_veniversvm_ColPsiCarabobo_api_internal_request_structs.UpdateSpecialtyRequest": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_handler.LoginRequest": {
            "type": "object",
            "required": [
                "identifier",
                "password"
            ],
            "properties": {
                "identifier": {
                    "type": "string",
                    "example": "admin"
                },
                "password": {
                    "type": "string",
                    "example": "admin123"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ColPsiCarabobo API",
	Description:      "Backend para la gestión del Colegio de Psicólogos de Carabobo.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
