// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Soporte Técnico",
            "email": "admin@colpsicarabobo.com"
        },
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registra un nuevo miembro del staff administrativo verificando la jerarquía de permisos.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administración - Gestión"
                ],
                "summary": "Crear un nuevo administrador",
                "parameters": [
                    {
                        "description": "Datos del nuevo administrador y permisos",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request_structs.CreateAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "message: creado correctamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "error: datos inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "error: violación de jerarquía",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/delete/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Realiza un borrado lógico del administrador. No permite auto-eliminación ni borrar SUDO.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administración - Gestión"
                ],
                "summary": "Eliminar administrador (Soft-delete)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID del administrador",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: eliminado correctamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "error: ID inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "error: permisos insuficientes",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna una lista paginada de administradores con soporte para búsqueda y caché.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administración - Gestión"
                ],
                "summary": "Listar administradores",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Número de página (def: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Registros por página (def: 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Búsqueda por username o email",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filtrar por estado activo (true/false)",
                        "name": "active",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "data, total, page, limit",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "error: fallo interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/update": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Modifica los datos y permisos de un administrador. Actualiza automáticamente la auditoría.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administración - Gestión"
                ],
                "summary": "Actualizar administrador",
                "parameters": [
                    {
                        "description": "Campos parciales a actualizar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request_structs.UpdateAdminRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: actualizado correctamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "error: permiso denegado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Valida las credenciales del administrador (email o username) y retorna un JWT dinámico.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Administración - Auth"
                ],
                "summary": "Iniciar sesión administrativo",
                "parameters": [
                    {
                        "description": "Credenciales de acceso",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message, token",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "error: formato inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "error: credenciales inválidas",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/psi/upload-csv": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Procesa un archivo CSV y crea registros. Solo accesible para administradores autorizados.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Psychologists"
                ],
                "summary": "Importar psicólogos masivamente",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Archivo CSV a procesar",
                        "name": "csv",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Retornado si el usuario no tiene permisos (Security by Obscurity)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.LoginRequest": {
            "type": "object",
            "required": [
                "identifier",
                "password"
            ],
            "properties": {
                "identifier": {
                    "type": "string",
                    "example": "admin"
                },
                "password": {
                    "type": "string",
                    "example": "admin123"
                }
            }
        },
        "request_structs.AdminPermissionsDTO": {
            "type": "object",
            "properties": {
                "can_create_admin": {
                    "type": "boolean"
                },
                "can_create_psi": {
                    "type": "boolean"
                },
                "can_create_tags": {
                    "type": "boolean"
                },
                "can_delete_admin": {
                    "type": "boolean"
                },
                "can_delete_psi": {
                    "type": "boolean"
                },
                "can_delete_publish": {
                    "type": "boolean"
                },
                "can_delete_tags": {
                    "type": "boolean"
                },
                "can_edit_tags": {
                    "type": "boolean"
                },
                "can_manage_notifications": {
                    "type": "boolean"
                },
                "can_publish": {
                    "type": "boolean"
                },
                "can_read_notifications": {
                    "type": "boolean"
                },
                "can_send_notifications": {
                    "type": "boolean"
                },
                "can_update_admin": {
                    "type": "boolean"
                },
                "can_update_psi": {
                    "type": "boolean"
                },
                "can_update_publish": {
                    "type": "boolean"
                }
            }
        },
        "request_structs.CreateAdminRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "permissions": {
                    "description": "Permisos que se le quieren asignar",
                    "allOf": [
                        {
                            "$ref": "#/definitions/request_structs.AdminPermissionsDTO"
                        }
                    ]
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "request_structs.UpdateAdminRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "permissions": {
                    "description": "Permisos",
                    "allOf": [
                        {
                            "$ref": "#/definitions/request_structs.AdminPermissionsDTO"
                        }
                    ]
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "ColPsiCarabobo API",
	Description:      "Pega solo tu token JWT. Swagger añadirá \"Bearer \" automáticamente.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
