// web/src/lib/geo.ts
// Catálogos geográficos de Venezuela usados por los formularios del panel.
// Reflejan las listas de validación del backend (api/internal/utils/geo_venezuela.go)
// para Carabobo y los estados; los municipios por estado son catálogo de presentación
// del frontend (el backend valida solo presencia en "municipio fuera de Carabobo").

export const MUNICIPIOS_CARABOBO: string[] = [
  "Bejuma",
  "Carlos Arvelo",
  "Diego Ibarra",
  "Guacara",
  "Juan José Mora",
  "Libertador",
  "Los Guayos",
  "Miranda",
  "Montalbán",
  "Naguanagua",
  "Puerto Cabello",
  "San Diego",
  "San Joaquín",
  "Valencia",
];

// Excluye Carabobo: la ubicación base se gestiona por separado (Presencia en Carabobo).
export const ESTADOS_VENEZUELA: string[] = [
  "Amazonas",
  "Anzoátegui",
  "Apure",
  "Aragua",
  "Barinas",
  "Bolívar",
  "Cojedes",
  "Delta Amacuro",
  "Dependencias Federales",
  "Distrito Capital",
  "Falcón",
  "Guárico",
  "Lara",
  "La Guaira",
  "Mérida",
  "Miranda",
  "Monagas",
  "Nueva Esparta",
  "Portuguesa",
  "Sucre",
  "Táchira",
  "Trujillo",
  "Yaracuy",
  "Zulia",
];

// Estados con Carabobo incluido (útil para filtros donde la base también aplica,
// p. ej. el seleccionador de destino en Notificaciones).
export const ESTADOS_VENEZUELA_INCL_CARABOBO: string[] = [
  "Carabobo",
  ...ESTADOS_VENEZUELA,
];

// Municipios de cada estado (catálogo nacional, Carabobo se gestiona aparte).
// "Dependencias Federales" no posee municipios ([]). Conteo oficial: estas 24
// entidades suman 321 municipios + los 14 de Carabobo = 335.
export const MUNICIPIOS_POR_ESTADO: Record<string, string[]> = {
  "Amazonas": [
    "Alto Orinoco",
    "Atabapo",
    "Atures",
    "Autana",
    "Manapiare",
    "Maroa",
    "Río Negro",
  ],
  "Anzoátegui": [
    "Anaco",
    "Aragua",
    "Diego Bautista Urbaneja",
    "Fernando de Peñalver",
    "Francisco del Carmen Carvajal",
    "Francisco de Miranda",
    "Guanta",
    "Independencia",
    "José Gregorio Monagas",
    "Juan Antonio Sotillo",
    "Juan Manuel Cajigal",
    "Libertad",
    "Manuel Ezequiel Bruzual",
    "Pedro María Freites",
    "Píritu",
    "San José de Guanipa",
    "San Juan de Capistrano",
    "Santa Ana",
    "Simón Bolívar",
    "Simón Rodríguez",
    "Sir Arthur McGregor",
  ],
  "Apure": [
    "Achaguas",
    "Biruaca",
    "Muñoz",
    "Páez",
    "Pedro Camejo",
    "Rómulo Gallegos",
    "San Fernando",
  ],
  "Aragua": [
    "Bolívar",
    "Camatagua",
    "Francisco Linares Alcántara",
    "Girardot",
    "José Ángel Lamas",
    "José Félix Ribas",
    "José Rafael Revenga",
    "Libertador",
    "Mario Briceño Iragorry",
    "Ocumare de la Costa de Oro",
    "San Casimiro",
    "San Sebastián",
    "Santiago Mariño",
    "Santos Michelena",
    "Sucre",
    "Tovar",
    "Urdaneta",
    "Zamora",
  ],
  "Barinas": [
    "Alberto Arvelo Torrealba",
    "Andrés Eloy Blanco",
    "Antonio José de Sucre",
    "Arismendi",
    "Barinas",
    "Bolívar",
    "Cruz Paredes",
    "Ezequiel Zamora",
    "Obispos",
    "Pedraza",
    "Santa Bárbara",
    "Sosa",
  ],
  "Bolívar": [
    "Angostura",
    "Caroní",
    "Cedeño",
    "El Callao",
    "Gran Sabana",
    "Heres",
    "Padre Pedro Chien",
    "Piar",
    "Roscio",
    "Sifontes",
    "Sucre",
  ],
  "Cojedes": [
    "Anzoátegui",
    "Ezequiel Zamora",
    "Girardot",
    "Lima Blanco",
    "Pao de San Juan Bautista",
    "Ricaurte",
    "Rómulo Gallegos",
    "San Carlos",
    "Tinaco",
  ],
  "Delta Amacuro": [
    "Antonio Díaz",
    "Casacoima",
    "Pedernales",
    "Tucupita",
  ],
  "Dependencias Federales": [],
  "Distrito Capital": ["Libertador"],
  "Falcón": [
    "Acosta",
    "Bolívar",
    "Buchivacoa",
    "Cacique Manaure",
    "Carirubana",
    "Colina",
    "Dabajuro",
    "Democracia",
    "Falcón",
    "Federación",
    "Jacura",
    "Los Taques",
    "Mauroa",
    "Miranda",
    "Monseñor Iturriza",
    "Palmasola",
    "Petit",
    "Píritu",
    "San Francisco",
    "Silva",
    "Sucre",
    "Tocópero",
    "Unión",
    "Urumaco",
    "Zamora",
  ],
  "Guárico": [
    "Camaguán",
    "Chaguaramas",
    "El Socorro",
    "Francisco de Miranda",
    "José Félix Ribas",
    "José Tadeo Monagas",
    "Juan Germán Roscio",
    "Julián Mellado",
    "Las Mercedes",
    "Leonardo Infante",
    "Ortiz",
    "Pedro Zaraza",
    "San Gerónimo de Guayabal",
    "San José de Guaribe",
    "Santa María de Ipire",
  ],
  "Lara": [
    "Andrés Eloy Blanco",
    "Crespo",
    "Iribarren",
    "Jiménez",
    "Morán",
    "Palavecino",
    "Simón Planas",
    "Torres",
    "Urdaneta",
  ],
  "La Guaira": ["Vargas"],
  "Mérida": [
    "Alberto Adriani",
    "Andrés Bello",
    "Antonio Pinto Salinas",
    "Aricagua",
    "Arzobispo Chacón",
    "Campo Elías",
    "Caracciolo Parra Olmedo",
    "Cardenal Quintero",
    "Guaraque",
    "Julio César Salas",
    "Justo Briceño",
    "Libertador",
    "Miranda",
    "Obispo Ramos de Lora",
    "Padre Noguera",
    "Pueblo Llano",
    "Rangel",
    "Rivas Dávila",
    "Santos Marquina",
    "Sucre",
    "Tovar",
    "Tulio Febres Cordero",
    "Zea",
  ],
  "Miranda": [
    "Acevedo",
    "Andrés Bello",
    "Baruta",
    "Brión",
    "Buroz",
    "Carrizal",
    "Chacao",
    "Cristóbal Rojas",
    "El Hatillo",
    "Guaicaipuro",
    "Independencia",
    "Lander",
    "Los Salias",
    "Páez",
    "Paz Castillo",
    "Pedro Gual",
    "Plaza",
    "Simón Bolívar",
    "Sucre",
    "Urdaneta",
    "Zamora",
  ],
  "Monagas": [
    "Acosta",
    "Aguasay",
    "Bolívar",
    "Caripe",
    "Cedeño",
    "Ezequiel Zamora",
    "Libertador",
    "Maturín",
    "Piar",
    "Punceres",
    "Santa Bárbara",
    "Sotillo",
    "Uracoa",
  ],
  "Nueva Esparta": [
    "Antolín del Campo",
    "Arismendi",
    "Díaz",
    "García",
    "Gómez",
    "Maneiro",
    "Marcano",
    "Mariño",
    "Península de Macanao",
    "Tubores",
    "Villalba",
  ],
  "Portuguesa": [
    "Agua Blanca",
    "Araure",
    "Esteller",
    "Guanare",
    "Guanarito",
    "José Vicente de Unda",
    "Ospino",
    "Páez",
    "Papelón",
    "San Genaro de Boconoíto",
    "San Rafael de Onoto",
    "Santa Rosalía",
    "Sucre",
    "Turén",
  ],
  "Sucre": [
    "Andrés Eloy Blanco",
    "Andrés Mata",
    "Arismendi",
    "Benítez",
    "Bermúdez",
    "Bolívar",
    "Cajigal",
    "Cruz Salmerón Acosta",
    "Libertador",
    "Mariño",
    "Mejía",
    "Montes",
    "Ribero",
    "Sucre",
    "Valdez",
  ],
  "Táchira": [
    "Andrés Bello",
    "Antonio Rómulo Costa",
    "Ayacucho",
    "Bolívar",
    "Cárdenas",
    "Córdoba",
    "Fernández Feo",
    "Francisco de Miranda",
    "García de Hevia",
    "Guásimos",
    "Independencia",
    "Jáuregui",
    "José María Vargas",
    "Junín",
    "Libertad",
    "Libertador",
    "Lobatera",
    "Michelena",
    "Panamericano",
    "Pedro María Ureña",
    "Rafael Urdaneta",
    "Samuel Darío Maldonado",
    "San Cristóbal",
    "San Judas Tadeo",
    "Seboruco",
    "Simón Rodríguez",
    "Sucre",
    "Torbes",
    "Uribante",
  ],
  "Trujillo": [
    "Andrés Bello",
    "Boconó",
    "Bolívar",
    "Candelaria",
    "Carache",
    "Escuque",
    "José Felipe Márquez Cañizales",
    "Juan Vicente Campo Elías",
    "La Ceiba",
    "Miranda",
    "Monte Carmelo",
    "Motatán",
    "Pampán",
    "Pampanito",
    "Rafael Rangel",
    "San Rafael de Carvajal",
    "Sucre",
    "Trujillo",
    "Urdaneta",
    "Valera",
  ],
  "Yaracuy": [
    "Arístides Bastidas",
    "Bolívar",
    "Bruzual",
    "Cocorote",
    "Independencia",
    "José Antonio Páez",
    "La Trinidad",
    "Manuel Monge",
    "Nirgua",
    "Peña",
    "San Felipe",
    "Sucre",
    "Urachiche",
    "Veroes",
  ],
  "Zulia": [
    "Almirante Padilla",
    "Baralt",
    "Cabimas",
    "Catatumbo",
    "Colón",
    "Francisco Javier Pulgar",
    "Guajira",
    "Jesús Enrique Lossada",
    "Jesús María Semprún",
    "La Cañada de Urdaneta",
    "Lagunillas",
    "Machiques de Perijá",
    "Mara",
    "Maracaibo",
    "Miranda",
    "Rosario de Perijá",
    "San Francisco",
    "Santa Rita",
    "Simón Bolívar",
    "Sucre",
    "Valmore Rodríguez",
  ],
};

// Municipios del estado indicado ([] si no tiene o no está en el catálogo).
export function municipiosDe(estado: string): string[] {
  return MUNICIPIOS_POR_ESTADO[estado] ?? [];
}