-- Migración: FIX-03 — Documentación del diseño de lifecycle de HMAC Keys
-- Fecha: 2026-07-25
--
-- ═══ DISEÑO APROBADO: UUID v7 + Cleanup Job (NO SHA-256) ═══
--
-- Las claves JWT se almacenan como UUID v7 en texto plano por las siguientes razones:
--
-- 1. RENDIMIENTO: La verificación de firma JWT es una comparación directa (HMAC-SHA256
--    con la key raw), sin necesidad de computar hash en cada request.
--
-- 2. EXPIRACIÓN IMPLÍCITA: UUID v7 embebe un timestamp preciso. El cleanup job
--    (cmd/cleanup/) ejecuta cada 30 minutos y limpia keys con timestamp >24h.
--    Esto invalida automáticamente tokens stale sin depender de JWT exp claim.
--
-- 3. INVALIDACIÓN INMEDIATA: Logout limpia la key (Key = ""), invalidate JWT
--    de forma inmediata sin esperar expiración.
--
-- 4. ROTACIÓN EN LOGIN: Cada login genera un UUID v7 nuevo, invalidando todos
--    los tokens anteriores del mismo usuario.
--
-- FLUJO DE SEGURIDAD:
--   Login → UUID v7 new key → store raw in DB → sign JWT with raw key
--   Logout → key set to "" → JWT invalid immediately
--   Cleanup (30min) → keys where UUID v7 timestamp > 24h → set to "" → JWT invalid
--   Password change → new UUID v7 key → old tokens invalidated
--
-- NO se requiere pgcrypto ni hashing SHA-256. La seguridad proviene del
-- lifecycle management, no de ocultar la key en la DB.

-- Migración intencionalmente vacía (documentación del diseño).
