# ── ETAPA DE CONSTRUCCIÓN ──────────────────────────────────────────────────
FROM golang:1.26-alpine AS builder

# Instalamos dependencias para CGO y libwebp
RUN apk add --no-cache \
    gcc \
    musl-dev \
    libwebp-dev \
    pkgconfig

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# CGO_ENABLED=1 es necesario para librerías de imágenes que dependen de C
RUN CGO_ENABLED=1 GOOS=linux go build -ldflags="-s -w" -o main ./cmd/api

# ── ETAPA FINAL (Imagen ligera) ─────────────────────────────────────────────
FROM alpine:3.19

# Instalamos certificados para TLS (SMTP/S3) y la librería de ejecución de webp
RUN apk --no-cache add \
    ca-certificates \
    tzdata \
    libwebp

WORKDIR /app
COPY --from=builder /app/main .
# Copiamos la carpeta de templates si el binario la necesita en runtime
COPY --from=builder /app/internal/templates ./internal/templates

EXPOSE 5555
CMD ["./main"]