services:
  # 1. Base de Datos real (Postgres) - Solo accesible internamente por PgBouncer y pgAdmin
  db:
    image: postgres:17-alpine
    container_name: colpsi_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    networks:
      - colpsi_network


  # 2. PgBouncer: El "embudo" de conexiones para la API
  pgbouncer:
    image: edoburu/pgbouncer
    container_name: colpsi_pgbouncer
    restart: always
    environment:
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-colpsi_db}
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=1000
      - DEFAULT_POOL_SIZE=20
      
      # --- CORRECCIÓN CRÍTICA ---
      # Cambiamos trust por scram-sha-256 para ser compatibles con Postgres 17
      - AUTH_TYPE=scram-sha-256 
      # Indicamos quién es el admin del pool
      - ADMIN_USERS=${DB_USER:-postgres} 
      
      # Parámetros ignorados (Vital para Go/GORM)
      - IGNORE_STARTUP_PARAMETERS=extra_float_digits,search_path
    ports:
      - "${PGBOUNCER_HOST_PORT:-6432}:5432"
    networks:
      - colpsi_network
    depends_on:
      - db

  # 3. pgAdmin: Para nosotros los devs
  pgadmin:
    image: dpage/pgadmin4
    container_name: colpsi_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - colpsi_network

  # 4. Almacenamiento S3 (MinIO)
  s3:
    image: minio/minio
    container_name: colpsi_s3
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID:-minioadmin}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY:-minioadmin}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - colpsi_network

  # 5. Helper para crear el bucket inicial
  createbuckets:
    image: minio/mc
    depends_on:
      - s3
    networks:
      - colpsi_network # <--- IMPORTANTE: Agregado para que resuelva el host 's3'
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://s3:9000 ${AWS_ACCESS_KEY_ID:-minioadmin} ${AWS_SECRET_ACCESS_KEY:-minioadmin}) do echo 'Esperando a MinIO...' && sleep 1; done;
      /usr/bin/mc mb --ignore-existing myminio/${AWS_S3_BUCKET:-colpsi-bucket};
      /usr/bin/mc anonymous set public myminio/${AWS_S3_BUCKET:-colpsi-bucket};
      exit 0;
      "

volumes:
  postgres_data:
  minio_data:

networks:
  colpsi_network:
    driver: bridge